# Generated by Django 5.0.4 on 2024-04-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("csv_upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="modified",
            field=models.DateTimeField(null=True),
        ),
    ]
