# Generated by Django 4.0.4 on 2022-05-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('amount', models.FloatField()),
                ('at', models.DateTimeField(db_index=True)),
            ],
            options={
                'get_latest_by': 'at',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTotal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aggregation.purchase',),
        ),
    ]
