# Generated by Django 4.0.5 on 2022-06-16 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
    ]
